# Generated by Django 5.2.1 on 2025-09-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="tags_suggested",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
